/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IOracleBondedKeeperInterface extends utils.Interface {
  functions: {
    "activate(address)": FunctionFragment;
    "addJob(address)": FunctionFragment;
    "addJobs(address[])": FunctionFragment;
    "bond(address,uint256)": FunctionFragment;
    "jobs()": FunctionFragment;
    "keep3r()": FunctionFragment;
    "keep3rV1Oracle()": FunctionFragment;
    "removeJob(address)": FunctionFragment;
    "unbond(address,uint256)": FunctionFragment;
    "updatePair(address)": FunctionFragment;
    "withdraw(address)": FunctionFragment;
    "workable(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "activate", values: [string]): string;
  encodeFunctionData(functionFragment: "addJob", values: [string]): string;
  encodeFunctionData(functionFragment: "addJobs", values: [string[]]): string;
  encodeFunctionData(
    functionFragment: "bond",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "jobs", values?: undefined): string;
  encodeFunctionData(functionFragment: "keep3r", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "keep3rV1Oracle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "removeJob", values: [string]): string;
  encodeFunctionData(
    functionFragment: "unbond",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "updatePair", values: [string]): string;
  encodeFunctionData(functionFragment: "withdraw", values: [string]): string;
  encodeFunctionData(functionFragment: "workable", values: [string]): string;

  decodeFunctionResult(functionFragment: "activate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addJobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "keep3r", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "keep3rV1Oracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unbond", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updatePair", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "workable", data: BytesLike): Result;

  events: {
    "JobAdded(address)": EventFragment;
    "JobRemoved(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "JobAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "JobRemoved"): EventFragment;
}

export type JobAddedEvent = TypedEvent<[string], { _job: string }>;

export type JobAddedEventFilter = TypedEventFilter<JobAddedEvent>;

export type JobRemovedEvent = TypedEvent<[string], { _job: string }>;

export type JobRemovedEventFilter = TypedEventFilter<JobRemovedEvent>;

export interface IOracleBondedKeeper extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IOracleBondedKeeperInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    activate(
      bonding: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addJob(
      _job: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addJobs(
      _jobs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bond(
      bonding: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    jobs(overrides?: CallOverrides): Promise<[string[]]>;

    keep3r(overrides?: CallOverrides): Promise<[string] & { _keep3r: string }>;

    keep3rV1Oracle(
      overrides?: CallOverrides
    ): Promise<[string] & { _keep3rV1Oracle: string }>;

    removeJob(
      _job: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unbond(
      bonding: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updatePair(
      _pair: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      bonding: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    workable(_pair: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  activate(
    bonding: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addJob(
    _job: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addJobs(
    _jobs: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bond(
    bonding: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  jobs(overrides?: CallOverrides): Promise<string[]>;

  keep3r(overrides?: CallOverrides): Promise<string>;

  keep3rV1Oracle(overrides?: CallOverrides): Promise<string>;

  removeJob(
    _job: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unbond(
    bonding: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updatePair(
    _pair: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    bonding: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  workable(_pair: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    activate(bonding: string, overrides?: CallOverrides): Promise<void>;

    addJob(_job: string, overrides?: CallOverrides): Promise<void>;

    addJobs(_jobs: string[], overrides?: CallOverrides): Promise<void>;

    bond(
      bonding: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    jobs(overrides?: CallOverrides): Promise<string[]>;

    keep3r(overrides?: CallOverrides): Promise<string>;

    keep3rV1Oracle(overrides?: CallOverrides): Promise<string>;

    removeJob(_job: string, overrides?: CallOverrides): Promise<void>;

    unbond(
      bonding: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updatePair(_pair: string, overrides?: CallOverrides): Promise<boolean>;

    withdraw(bonding: string, overrides?: CallOverrides): Promise<void>;

    workable(_pair: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "JobAdded(address)"(_job?: null): JobAddedEventFilter;
    JobAdded(_job?: null): JobAddedEventFilter;

    "JobRemoved(address)"(_job?: null): JobRemovedEventFilter;
    JobRemoved(_job?: null): JobRemovedEventFilter;
  };

  estimateGas: {
    activate(
      bonding: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addJob(
      _job: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addJobs(
      _jobs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bond(
      bonding: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    jobs(overrides?: CallOverrides): Promise<BigNumber>;

    keep3r(overrides?: CallOverrides): Promise<BigNumber>;

    keep3rV1Oracle(overrides?: CallOverrides): Promise<BigNumber>;

    removeJob(
      _job: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unbond(
      bonding: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updatePair(
      _pair: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      bonding: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    workable(_pair: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    activate(
      bonding: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addJob(
      _job: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addJobs(
      _jobs: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bond(
      bonding: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    jobs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    keep3r(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    keep3rV1Oracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeJob(
      _job: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unbond(
      bonding: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updatePair(
      _pair: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      bonding: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    workable(
      _pair: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
