/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IStealthRelayerInterface extends utils.Interface {
  functions: {
    "addJob(address)": FunctionFragment;
    "addJobs(address[])": FunctionFragment;
    "caller()": FunctionFragment;
    "execute(address,bytes,bytes32,uint256)": FunctionFragment;
    "executeAndPay(address,bytes,bytes32,uint256,uint256)": FunctionFragment;
    "executeWithoutBlockProtection(address,bytes,bytes32)": FunctionFragment;
    "executeWithoutBlockProtectionAndPay(address,bytes,bytes32,uint256)": FunctionFragment;
    "forceBlockProtection()": FunctionFragment;
    "jobs()": FunctionFragment;
    "penalty()": FunctionFragment;
    "removeJob(address)": FunctionFragment;
    "removeJobs(address[])": FunctionFragment;
    "setForceBlockProtection(bool)": FunctionFragment;
    "setPenalty(uint256)": FunctionFragment;
    "setStealthVault(address)": FunctionFragment;
    "stealthVault()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addJob", values: [string]): string;
  encodeFunctionData(functionFragment: "addJobs", values: [string[]]): string;
  encodeFunctionData(functionFragment: "caller", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [string, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeAndPay",
    values: [string, BytesLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithoutBlockProtection",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithoutBlockProtectionAndPay",
    values: [string, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "forceBlockProtection",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "jobs", values?: undefined): string;
  encodeFunctionData(functionFragment: "penalty", values?: undefined): string;
  encodeFunctionData(functionFragment: "removeJob", values: [string]): string;
  encodeFunctionData(
    functionFragment: "removeJobs",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setForceBlockProtection",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPenalty",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStealthVault",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "stealthVault",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addJobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "caller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeAndPay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeWithoutBlockProtection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeWithoutBlockProtectionAndPay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forceBlockProtection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jobs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "penalty", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeJobs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setForceBlockProtection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPenalty", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setStealthVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stealthVault",
    data: BytesLike
  ): Result;

  events: {
    "MigratedStealthVault(address)": EventFragment;
    "PenaltySet(uint256)": EventFragment;
    "StealthVaultSet(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "MigratedStealthVault"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PenaltySet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StealthVaultSet"): EventFragment;
}

export type MigratedStealthVaultEvent = TypedEvent<
  [string],
  { _migratedTo: string }
>;

export type MigratedStealthVaultEventFilter =
  TypedEventFilter<MigratedStealthVaultEvent>;

export type PenaltySetEvent = TypedEvent<[BigNumber], { _penalty: BigNumber }>;

export type PenaltySetEventFilter = TypedEventFilter<PenaltySetEvent>;

export type StealthVaultSetEvent = TypedEvent<
  [string],
  { _stealthVault: string }
>;

export type StealthVaultSetEventFilter = TypedEventFilter<StealthVaultSetEvent>;

export interface IStealthRelayer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IStealthRelayerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addJob(
      _job: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addJobs(
      _jobsList: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    caller(overrides?: CallOverrides): Promise<[string] & { _caller: string }>;

    execute(
      _address: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      _blockNumber: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeAndPay(
      _address: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      _blockNumber: BigNumberish,
      _payment: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeWithoutBlockProtection(
      _address: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeWithoutBlockProtectionAndPay(
      _job: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      _payment: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    forceBlockProtection(
      overrides?: CallOverrides
    ): Promise<[boolean] & { _forceBlockProtection: boolean }>;

    jobs(
      overrides?: CallOverrides
    ): Promise<[string[]] & { _jobsList: string[] }>;

    penalty(overrides?: CallOverrides): Promise<[BigNumber]>;

    removeJob(
      _job: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeJobs(
      _jobsList: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setForceBlockProtection(
      _forceBlockProtection: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPenalty(
      _penalty: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setStealthVault(
      _stealthVault: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stealthVault(overrides?: CallOverrides): Promise<[string]>;
  };

  addJob(
    _job: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addJobs(
    _jobsList: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  caller(overrides?: CallOverrides): Promise<string>;

  execute(
    _address: string,
    _callData: BytesLike,
    _stealthHash: BytesLike,
    _blockNumber: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeAndPay(
    _address: string,
    _callData: BytesLike,
    _stealthHash: BytesLike,
    _blockNumber: BigNumberish,
    _payment: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeWithoutBlockProtection(
    _address: string,
    _callData: BytesLike,
    _stealthHash: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeWithoutBlockProtectionAndPay(
    _job: string,
    _callData: BytesLike,
    _stealthHash: BytesLike,
    _payment: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  forceBlockProtection(overrides?: CallOverrides): Promise<boolean>;

  jobs(overrides?: CallOverrides): Promise<string[]>;

  penalty(overrides?: CallOverrides): Promise<BigNumber>;

  removeJob(
    _job: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeJobs(
    _jobsList: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setForceBlockProtection(
    _forceBlockProtection: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPenalty(
    _penalty: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setStealthVault(
    _stealthVault: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stealthVault(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addJob(_job: string, overrides?: CallOverrides): Promise<void>;

    addJobs(_jobsList: string[], overrides?: CallOverrides): Promise<void>;

    caller(overrides?: CallOverrides): Promise<string>;

    execute(
      _address: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      _blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    executeAndPay(
      _address: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      _blockNumber: BigNumberish,
      _payment: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    executeWithoutBlockProtection(
      _address: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    executeWithoutBlockProtectionAndPay(
      _job: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      _payment: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    forceBlockProtection(overrides?: CallOverrides): Promise<boolean>;

    jobs(overrides?: CallOverrides): Promise<string[]>;

    penalty(overrides?: CallOverrides): Promise<BigNumber>;

    removeJob(_job: string, overrides?: CallOverrides): Promise<void>;

    removeJobs(_jobsList: string[], overrides?: CallOverrides): Promise<void>;

    setForceBlockProtection(
      _forceBlockProtection: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setPenalty(
      _penalty: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setStealthVault(
      _stealthVault: string,
      overrides?: CallOverrides
    ): Promise<void>;

    stealthVault(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "MigratedStealthVault(address)"(
      _migratedTo?: null
    ): MigratedStealthVaultEventFilter;
    MigratedStealthVault(_migratedTo?: null): MigratedStealthVaultEventFilter;

    "PenaltySet(uint256)"(_penalty?: null): PenaltySetEventFilter;
    PenaltySet(_penalty?: null): PenaltySetEventFilter;

    "StealthVaultSet(address)"(
      _stealthVault?: null
    ): StealthVaultSetEventFilter;
    StealthVaultSet(_stealthVault?: null): StealthVaultSetEventFilter;
  };

  estimateGas: {
    addJob(
      _job: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addJobs(
      _jobsList: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    caller(overrides?: CallOverrides): Promise<BigNumber>;

    execute(
      _address: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      _blockNumber: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeAndPay(
      _address: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      _blockNumber: BigNumberish,
      _payment: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeWithoutBlockProtection(
      _address: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeWithoutBlockProtectionAndPay(
      _job: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      _payment: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    forceBlockProtection(overrides?: CallOverrides): Promise<BigNumber>;

    jobs(overrides?: CallOverrides): Promise<BigNumber>;

    penalty(overrides?: CallOverrides): Promise<BigNumber>;

    removeJob(
      _job: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeJobs(
      _jobsList: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setForceBlockProtection(
      _forceBlockProtection: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPenalty(
      _penalty: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setStealthVault(
      _stealthVault: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stealthVault(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addJob(
      _job: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addJobs(
      _jobsList: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    caller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    execute(
      _address: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      _blockNumber: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeAndPay(
      _address: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      _blockNumber: BigNumberish,
      _payment: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeWithoutBlockProtection(
      _address: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeWithoutBlockProtectionAndPay(
      _job: string,
      _callData: BytesLike,
      _stealthHash: BytesLike,
      _payment: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    forceBlockProtection(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    jobs(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    penalty(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeJob(
      _job: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeJobs(
      _jobsList: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setForceBlockProtection(
      _forceBlockProtection: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPenalty(
      _penalty: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setStealthVault(
      _stealthVault: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stealthVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
