/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  GenericKeep3rV2,
  GenericKeep3rV2Interface,
} from "../GenericKeep3rV2";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "KP3R",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "WETH",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "keep3rHelper",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "requiredHarvest",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "requiredTend",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "slidingOracle",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610194806100206000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c806305e0b9a0146100675780637f04f1581461009f57806383acafc4146100cd578063a9092411146100e0578063ad5c464814610100578063f11a1d1a1461011b575b600080fd5b610082731ceb5cb57c4d4e2b2433641b95dd330a33185a4481565b6040516001600160a01b0390911681526020015b60405180910390f35b6100bf6100ad36600461012e565b60036020526000908152604090205481565b604051908152602001610096565b600554610082906001600160a01b031681565b6100bf6100ee36600461012e565b60026020526000908152604090205481565b61008273c02aaa39b223fe8d0a0e5c4f27ead9083c756cc281565b600454610082906001600160a01b031681565b60006020828403121561014057600080fd5b81356001600160a01b038116811461015757600080fd5b939250505056fea2646970667358221220548d89213f9126fcf0123eee4947d9f32e0d614010af6ef987de68e74e20ba9c64736f6c63430008090033";

type GenericKeep3rV2ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: GenericKeep3rV2ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class GenericKeep3rV2__factory extends ContractFactory {
  constructor(...args: GenericKeep3rV2ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<GenericKeep3rV2> {
    return super.deploy(overrides || {}) as Promise<GenericKeep3rV2>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): GenericKeep3rV2 {
    return super.attach(address) as GenericKeep3rV2;
  }
  connect(signer: Signer): GenericKeep3rV2__factory {
    return super.connect(signer) as GenericKeep3rV2__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): GenericKeep3rV2Interface {
    return new utils.Interface(_abi) as GenericKeep3rV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): GenericKeep3rV2 {
    return new Contract(address, _abi, signerOrProvider) as GenericKeep3rV2;
  }
}
