/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICrvStrategyKeep3rJobV2,
  ICrvStrategyKeep3rJobV2Interface,
} from "../ICrvStrategyKeep3rJobV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_strategy",
        type: "address",
      },
    ],
    name: "forceWorkUnsafe",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_v2Keeper",
        type: "address",
      },
    ],
    name: "setV2Keep3r",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_strategy",
        type: "address",
      },
    ],
    name: "strategyIsV1",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "v2Keeper",
    outputs: [
      {
        internalType: "address",
        name: "_v2Keeper",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICrvStrategyKeep3rJobV2__factory {
  static readonly abi = _abi;
  static createInterface(): ICrvStrategyKeep3rJobV2Interface {
    return new utils.Interface(_abi) as ICrvStrategyKeep3rJobV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICrvStrategyKeep3rJobV2 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ICrvStrategyKeep3rJobV2;
  }
}
