/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IUni, IUniInterface } from "../IUni";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "address[]",
        name: "path",
        type: "address[]",
      },
    ],
    name: "getAmountsOut",
    outputs: [
      {
        internalType: "uint256[]",
        name: "amounts",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUni__factory {
  static readonly abi = _abi;
  static createInterface(): IUniInterface {
    return new utils.Interface(_abi) as IUniInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IUni {
    return new Contract(address, _abi, signerOrProvider) as IUni;
  }
}
