/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IV2Keeper, IV2KeeperInterface } from "../IV2Keeper";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_job",
        type: "address",
      },
    ],
    name: "JobAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_job",
        type: "address",
      },
    ],
    name: "JobRemoved",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_job",
        type: "address",
      },
    ],
    name: "addJob",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "_jobs",
        type: "address[]",
      },
    ],
    name: "addJobs",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_strategy",
        type: "address",
      },
    ],
    name: "harvest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "jobs",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_job",
        type: "address",
      },
    ],
    name: "removeJob",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_strategy",
        type: "address",
      },
    ],
    name: "tend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IV2Keeper__factory {
  static readonly abi = _abi;
  static createInterface(): IV2KeeperInterface {
    return new utils.Interface(_abi) as IV2KeeperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IV2Keeper {
    return new Contract(address, _abi, signerOrProvider) as IV2Keeper;
  }
}
