/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IV2Keep3rStealthJob,
  IV2Keep3rStealthJobInterface,
} from "../IV2Keep3rStealthJob";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_strategy",
        type: "address",
      },
    ],
    name: "forceWorkUnsafe",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IV2Keep3rStealthJob__factory {
  static readonly abi = _abi;
  static createInterface(): IV2Keep3rStealthJobInterface {
    return new utils.Interface(_abi) as IV2Keep3rStealthJobInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IV2Keep3rStealthJob {
    return new Contract(address, _abi, signerOrProvider) as IV2Keep3rStealthJob;
  }
}
