/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IV2Vault, IV2VaultInterface } from "../IV2Vault";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_index",
        type: "uint256",
      },
    ],
    name: "withdrawalQueue",
    outputs: [
      {
        internalType: "address",
        name: "_strategy",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IV2Vault__factory {
  static readonly abi = _abi;
  static createInterface(): IV2VaultInterface {
    return new utils.Interface(_abi) as IV2VaultInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IV2Vault {
    return new Contract(address, _abi, signerOrProvider) as IV2Vault;
  }
}
