/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Keep3r, Keep3rInterface } from "../Keep3r";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_bond",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_minBond",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_earned",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_age",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "_onlyEOA",
        type: "bool",
      },
    ],
    name: "Keep3rRequirementsSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_keep3r",
        type: "address",
      },
    ],
    name: "Keep3rSet",
    type: "event",
  },
  {
    inputs: [],
    name: "age",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "bond",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "earned",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "keep3r",
    outputs: [
      {
        internalType: "address",
        name: "_keep3r",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "minBond",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "onlyEOA",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_keep3r",
        type: "address",
      },
    ],
    name: "setKeep3r",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_bond",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_minBond",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_earned",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_age",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_onlyEOA",
        type: "bool",
      },
    ],
    name: "setKeep3rRequirements",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Keep3r__factory {
  static readonly abi = _abi;
  static createInterface(): Keep3rInterface {
    return new utils.Interface(_abi) as Keep3rInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Keep3r {
    return new Contract(address, _abi, signerOrProvider) as Keep3r;
  }
}
