/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Zap, ZapInterface } from "../Zap";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "int128",
        name: "",
        type: "int128",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "remove_liquidity_one_coin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Zap__factory {
  static readonly abi = _abi;
  static createInterface(): ZapInterface {
    return new utils.Interface(_abi) as ZapInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Zap {
    return new Contract(address, _abi, signerOrProvider) as Zap;
  }
}
